title: Manusaporn Treerungroj
logo: /profile.jpg
description: ğŸ‘©â€ğŸ”¬ Data Scientist | ğŸ¦Š FOXFOX Co-Founder | Noob Learning Owner | Certified Tensorflow Developer
show_downloads: false
theme: jekyll-theme-minimal
